In [2]:
import numpy as np

In [18]:
import numpy as np
Employee_rating = np.array([1, 4, 3, 5, 6, 8, 9, 10, 12])
print(Employee_rating[0:7])

[1 4 3 5 6 8 9]


In [19]:
Books = np.array(['Physics', 'DataScience', 'Maths', 'Python', 'Hadoop', 'OPPs', 'Java', 'Cloud'])
print(Books[5:])

['OPPs' 'Java' 'Cloud']


In [20]:
#Negative slicing for 1D array
Neg_slice = np.array([13, 34, 58, 69, 44, 56, 37, 24])
print(Neg_slice[1:-1])

[34 58 69 44 56 37]


In [5]:
Z=np.array([11,22,33,44,55])
print(Z)
print(Z.ndim)

[11 22 33 44 55]
1


In [4]:
Z=np.array([[11,22,33,44,55],[66,77,88,99,100]])
print(Z)
print(Z.ndim)

[[ 11  22  33  44  55]
 [ 66  77  88  99 100]]
2


In [8]:
import numpy as np
array_3d = np.array([
    [[1, 2, 3], [4, 5, 6]],      
    [[7, 8, 9], [10, 11, 12]]    
])

print("Shape:", array_3d.shape)  # Output: (2, 2, 3)

print("Array:")
print(array_3d)
print(array_3d[0][1][1:]) 

Shape: (2, 2, 3)
Array:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[5 6]


In [15]:
#NEGATIVE INDEXING
arr=np.array([1,2,3,4])
print(arr[-2::])

[3 4]


In [16]:
arr1=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
print(arr1)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [21]:
# Create a 1D NumPy array with at least 15 elements
array_1d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18])
print("1D Array:", array_1d)

# Create a 2D NumPy array with a minimum of 4 rows and 5 columns
array_2d = np.array([[1, 2, 3, 4, 5],
                     [6, 7, 8, 9, 10],
                     [11, 12, 13, 14, 15],
                     [16, 17, 18, 19, 20],
                     [21, 22, 23, 24, 25]])
print("2D Array:\n", array_2d)

# Create a 3D NumPy array with at least 2 matrices, each containing 3 rows and 4 columns
array_3d = np.array([[[1, 2, 3, 4],
                      [5, 6, 7, 8],
                      [9, 10, 11, 12]],
                     [[13, 14, 15, 16],
                      [17, 18, 19, 20],
                      [21, 22, 23, 24]]])
print("3D Array:\n", array_3d)

print("Original array:", array_1d)
print("First 5 elements [0:5]:", array_1d[0:5])
print("Every second element [::2]:", array_1d[::2])
print("Elements from index 5 to 10 [5:11]:", array_1d[5:11])
print("Last 5 elements [-5:]:", array_1d[-5:])
print("Every third element starting from index 2 [2::3]:", array_1d[2::3])
print("Reverse array [::-1]:", array_1d[::-1])

print("Original 2D array:\n", array_2d)
print("First 2 rows [0:2]:\n", array_2d[0:2])
print("Last 3 columns [:, -3:]:\n", array_2d[:, -3:])
print("First 3 rows and first 3 columns [0:3, 0:3]:\n", array_2d[0:3, 0:3])
print("Every second row [::2]:\n", array_2d[::2])
print("Middle columns (index 1-3) [:, 1:4]:\n", array_2d[:, 1:4])

print("Original 3D array:\n", array_3d)
print("First matrix [0]:\n", array_3d[0])
print("Second matrix, first 2 rows [1, 0:2]:\n", array_3d[1, 0:2])
print("All matrices, middle row, all columns [:, 1, :]:\n", array_3d[:, 1, :])
print("First matrix, all rows, last 2 columns [0, :, -2:]:\n", array_3d[0, :, -2:])
print("Second matrix, second row, middle 2 elements [1, 1, 1:3]:", array_3d[1, 1, 1:3])


# Negative slicing on 1D array
print("1D negative slicing:")
print("Remove first and last element [1:-1]:", array_1d[1:-1])
print("Last 3 elements [-3:]:", array_1d[-3:])
print("All but last 2 elements [:-2]:", array_1d[:-2])

# Negative slicing on 2D array
print("\n2D negative slicing:")
print("Remove first and last row [1:-1]:\n", array_2d[1:-1])
print("Remove first and last column [:, 1:-1]:\n", array_2d[:, 1:-1])
print("Remove borders [1:-1, 1:-1]:\n", array_2d[1:-1, 1:-1])

# Negative slicing on 3D array
print("\n3D negative slicing:")
print("Second matrix, remove first and last row [1, 1:-1]:\n", array_3d[1, 1:-1])
print("All matrices, remove first and last column [:, :, 1:-1]:\n", array_3d[:, :, 1:-1])

print("Original 1D array:", array_1d)
print("Positive slicing [2:16]:", array_1d[2:16])
print("Negative slicing [2:-2]:", array_1d[2:-2])
print("Both give same result:", np.array_equal(array_1d[2:16], array_1d[2:-2]))

print("\nOriginal 2D array shape:", array_2d.shape)
print("Positive slicing [1:4, 1:4] shape:", array_2d[1:4, 1:4].shape)
print("Negative slicing [1:-1, 1:-1] shape:", array_2d[1:-1, 1:-1].shape)
print("Results are equal:", np.array_equal(array_2d[1:4, 1:4], array_2d[1:-1, 1:-1]))

1D Array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]
2D Array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
3D Array:
 [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
Original array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]
First 5 elements [0:5]: [1 2 3 4 5]
Every second element [::2]: [ 1  3  5  7  9 11 13 15 17]
Elements from index 5 to 10 [5:11]: [ 6  7  8  9 10 11]
Last 5 elements [-5:]: [14 15 16 17 18]
Every third element starting from index 2 [2::3]: [ 3  6  9 12 15 18]
Reverse array [::-1]: [18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1]
Original 2D array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
First 2 rows [0:2]:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Last 3 columns [:, -3:]:
 [[ 3  4  5]
 [ 8  9 10]
 [13 14 15]
 [18 19 20]
 [23 24 25]]
First 3 rows and first 3 columns [0:3, 0:3]:
 [[ 1  2  3