In [170]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [171]:
df=pd.read_csv("Social_Network_Ads.csv")
df

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [172]:
df.isna().sum()

User ID            0
Gender             0
Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

In [173]:
df.columns

Index(['User ID', 'Gender', 'Age', 'EstimatedSalary', 'Purchased'], dtype='object')

In [174]:
df.describe()

User ID         Age  EstimatedSalary   Purchased
count  4.000000e+02  400.000000       400.000000  400.000000
mean   1.569154e+07   37.655000     69742.500000    0.357500
std    7.165832e+04   10.482877     34096.960282    0.479864
min    1.556669e+07   18.000000     15000.000000    0.000000
25%    1.562676e+07   29.750000     43000.000000    0.000000
50%    1.569434e+07   37.000000     70000.000000    0.000000
75%    1.575036e+07   46.000000     88000.000000    1.000000
max    1.581524e+07   60.000000    150000.000000    1.000000

In [175]:
df['Purchased'].value_counts()

Purchased
0    257
1    143
Name: count, dtype: int64

In [176]:
Gender=pd.get_dummies(df['Gender'],drop_first=True)

In [177]:
df=pd.concat([df,Gender],axis=1)

In [178]:
df.drop(['Gender'],axis=1,inplace=True)

In [179]:
df

User ID  Age  EstimatedSalary  Purchased   Male
0    15624510   19            19000          0   True
1    15810944   35            20000          0   True
2    15668575   26            43000          0  False
3    15603246   27            57000          0  False
4    15804002   19            76000          0   True
..        ...  ...              ...        ...    ...
395  15691863   46            41000          1  False
396  15706071   51            23000          1   True
397  15654296   50            20000          1  False
398  15755018   36            33000          0   True
399  15594041   49            36000          1  False

[400 rows x 5 columns]

In [180]:
X = df[['Male', 'Age', 'EstimatedSalary']]
y= df['Purchased']

In [181]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()

In [182]:
scaler.fit(X)

StandardScaler()

In [183]:
scaled_features=scaler.transform(X)
scaled_features

array([[ 1.02020406, -1.78179743, -1.49004624],
       [ 1.02020406, -0.25358736, -1.46068138],
       [-0.98019606, -1.11320552, -0.78528968],
       ...,
       [-0.98019606,  1.17910958, -1.46068138],
       [ 1.02020406, -0.15807423, -1.07893824],
       [-0.98019606,  1.08359645, -0.99084367]], shape=(400, 3))

In [198]:
df_feat = pd.DataFrame(scaled_features,columns=X.columns)
df_feat.head()

Male       Age  EstimatedSalary
0  1.020204 -1.781797        -1.490046
1  1.020204 -0.253587        -1.460681
2 -0.980196 -1.113206        -0.785290
3 -0.980196 -1.017692        -0.374182
4  1.020204 -1.781797         0.183751

In [199]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [200]:
from sklearn.neighbors import KNeighborsClassifier

In [217]:
# 6. Apply KNN
knn = KNeighborsClassifier(n_neighbors=3)  
knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=3)

In [218]:
pred=knn.predict(X_test)
pred

array([0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1])

In [219]:
print(confusion_matrix(y_test,pred))

[[47  2]
 [ 7 24]]


In [220]:
print(classification_report(y_test,pred))

              precision    recall  f1-score   support

           0       0.87      0.96      0.91        49
           1       0.92      0.77      0.84        31

    accuracy                           0.89        80
   macro avg       0.90      0.87      0.88        80
weighted avg       0.89      0.89      0.89        80

