In [1]:
!pip install numpy


[notice] A new release of pip is available: 25.0.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

In [3]:
dir(np)

['ALLOW_THREADS',
 'BUFSIZE',
 'CLIP',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_builtins',
 '_distributor_init',
 '_financi

In [4]:
array_0d=np.array(2)

In [5]:
print(array_0d)

2


In [7]:
array_1d=np.array([1,2,3,50,60,70])
array_1d


array([ 1,  2,  3, 50, 60, 70])

In [8]:
array_1d.ndim

1

In [11]:
array_2d=np.array([[1,5,6],[8,6,7],[10,20,30]])
array_2d

array([[ 1,  5,  6],
       [ 8,  6,  7],
       [10, 20, 30]])

In [15]:
array_22d=np.array([[1,5],[8,6],[10,20]])
array_22d

array([[ 1,  5],
       [ 8,  6],
       [10, 20]])

In [16]:
array_22d.shape

(3, 2)

In [17]:
array_22d.reshape(2,3)

array([[ 1,  5,  8],
       [ 6, 10, 20]])

In [19]:
array_22d.flatten()

array([ 1,  5,  8,  6, 10, 20])

In [22]:
array_22d.transpose()

array([[ 1,  8, 10],
       [ 5,  6, 20]])

In [23]:
a=np.array([30,20,10])
b=np.array([10,20,30])
add=np.add(a,b)
print(add)

[40 40 40]


In [12]:
array_3d=np.array([[[1,5,6],[10,20,30]],[[12,13,14],[18,19,31]]])
array_3d

array([[[ 1,  5,  6],
        [10, 20, 30]],

       [[12, 13, 14],
        [18, 19, 31]]])

In [13]:
#temperature=[[75.2,77.1,74.5,79.3,82.6,81.2,77.8],[78,88,76,75,79,70,72]]
#explore the key attributes of numpy arrays ndim,shape,size,dtype,itemsize,and data
#demonstrate important numpy array function such as reshape,flatten and transponse
import numpy as np
temperature = [
    [75.2, 77.1, 74.5, 79.3, 82.6, 81.2, 77.8],
    [78, 88, 76, 75, 79, 70, 72]
]
# Convert to NumPy array
arr = np.array(temperature)
# Key Attributes
print("Original Array:\n", arr)
print("\nKey Attributes:")
print("Number of dimensions (ndim):", arr.ndim)
print("Shape (rows, columns):", arr.shape)
print("Total elements (size):", arr.size)
print("Data type (dtype):", arr.dtype)
print("Size of each element in bytes (itemsize):", arr.itemsize)
# NumPy Functions
print("\nReshaped to (7, 2):\n", arr.reshape(7, 2))
print("\nFlattened to 1D array:\n", arr.flatten())
print("\nTransposed array (rows <-> columns):\n", arr.transpose())


Original Array:
 [[75.2 77.1 74.5 79.3 82.6 81.2 77.8]
 [78.  88.  76.  75.  79.  70.  72. ]]

Key Attributes:
Number of dimensions (ndim): 2
Shape (rows, columns): (2, 7)
Total elements (size): 14
Data type (dtype): float64
Size of each element in bytes (itemsize): 8

Reshaped to (7, 2):
 [[75.2 77.1]
 [74.5 79.3]
 [82.6 81.2]
 [77.8 78. ]
 [88.  76. ]
 [75.  79. ]
 [70.  72. ]]

Flattened to 1D array:
 [75.2 77.1 74.5 79.3 82.6 81.2 77.8 78.  88.  76.  75.  79.  70.  72. ]

Transposed array (rows <-> columns):
 [[75.2 78. ]
 [77.1 88. ]
 [74.5 76. ]
 [79.3 75. ]
 [82.6 79. ]
 [81.2 70. ]
 [77.8 72. ]]
