In [1]:
import numpy as np
random_data = np.random.randint(10, 50, size = (5, 4))

In [2]:
random_data

array([[12, 39, 28, 40],
       [37, 20, 23, 24],
       [16, 31, 15, 28],
       [43, 38, 13, 43],
       [23, 49, 30, 34]], dtype=int32)

In [3]:
random_data.min(axis=0) #minimum of every columnwise

array([12, 20, 13, 24], dtype=int32)

In [4]:
random_data.min(axis=1) #minimum of every rowwise

array([12, 20, 15, 13, 23], dtype=int32)

In [5]:
random_data.sum()

np.int64(586)

In [6]:
random_data.sum(axis=0)

array([131, 177, 109, 169])

In [7]:
random_data.sum(axis=1)

array([119, 104,  90, 137, 136])

In [8]:
total=random_data.sum(axis=1)
total

array([119, 104,  90, 137, 136])

In [9]:
random_data.min() # minimum of all set

np.int32(12)

In [10]:
total.argmin() ##

np.int64(2)

In [11]:
total.argmax()

np.int64(3)

In [12]:
import numpy as np

# 1. Create a 2D NumPy array for 10 years (rows) and 5 cities (columns)
np.random.seed(0)  # For reproducibility
emissions = np.random.randint(1000, 5001, size=(10, 5))
print("Carbon Emissions Data (tons):\n", emissions)

# 2. Total emissions for each city over 10 years (sum along rows)
total_emissions_per_city = np.sum(emissions, axis=0)
print("\nTotal emissions per city over 10 years:\n", total_emissions_per_city)

# 3. Find the year with the highest total emissions (sum along columns)
total_emissions_per_year = np.sum(emissions, axis=1)
year_with_max_emissions = np.argmax(total_emissions_per_year) + 1  # +1 for 1-based indexing
print(f"\nYear with the highest total emissions: Year {year_with_max_emissions}")

# 4. Calculate average emissions for all cities in Year 5 (index 4)
average_year5 = np.mean(emissions[4])
print(f"\nAverage emissions for all cities in Year 5: {average_year5:.2f} tons")

Carbon Emissions Data (tons):
 [[3732 3607 2653 4264 1835]
 [1763 2731 4431 2033 4795]
 [1277 2778 2828 3647 4142]
 [4544 3648 4468 3362 1705]
 [4558 3599 3135 3222 4672]
 [3897 2701 1537 3893 3120]
 [3825 2940 3163 1976 1755]
 [4781 3046 2871 4503 3496]
 [3898 1099 3008 4249 1755]
 [1797 1659 4219 3958 1423]]

Total emissions per city over 10 years:
 [34072 27808 32313 35107 28698]

Year with the highest total emissions: Year 5

Average emissions for all cities in Year 5: 3837.20 tons


In [14]:
data=np.random.randint(10,60,size=20)
print(data)

[11 19 42 41 20 33 45 21 38 44 10 10 46 15 48 50 27 25 14 51]


In [16]:
avg_data=np.mean(data)
print("Average:")
print(avg_data)

Average:
30.5


In [20]:
#years in which value is below 20
for i in range(0,20):
    if data[i]<20:
        print(i+1)


1
2
11
12
14
19


In [24]:
below_20=np.where(data<=20)[0]+1
below_20

array([ 1,  2,  5, 11, 12, 14, 19])

In [26]:
high_per=data.max()
high_per

np.int32(51)

In [31]:
##Question 3
water_usage = np.random.randint(5000, 20000, size=(12, 5))
print("Water Usage Data (liters):\n", water_usage)

Water Usage Data (liters):
 [[ 8533  7937 14837  9939 14744]
 [ 8224 10021 15389  6134  5025]
 [14680  5956  6913  7934 18429]
 [14661 18907  7721 15088  5928]
 [10627 16003 11265 10446  5469]
 [15527 13717  6863  6720 10272]
 [ 5591 11185  7322 16702  5207]
 [ 9262 19447  8421 17281 10249]
 [15102 16052 13408 13216 17355]
 [16218 10103 12939  7282  6740]
 [11118 17579 10846 18310  8781]
 [ 7775  7603 19368 12179 18928]]


In [32]:
# Step 2: Total water usage for each field over the year
total_usage_per_field = np.sum(water_usage, axis=0)
print("\nTotal Water Usage per Field (Yearly):", total_usage_per_field)



Total Water Usage per Field (Yearly): [137318 154510 135292 141231 127127]


In [33]:
# Step 3: Find the month with the highest water usage across all fields
monthly_totals = np.sum(water_usage, axis=1)
month_highest_usage = np.argmax(monthly_totals) + 1  
print("\nMonth with Highest Total Water Usage:", month_highest_usage)


Month with Highest Total Water Usage: 9


In [34]:
# Step 4: Calculate the average water usage for all fields in a specific month (e.g., February = index 1)
february_average = np.mean(water_usage[1])
print("\nAverage Water Usage in February:", february_average)


Average Water Usage in February: 8958.6
